baseURL = "http://192.168.1.21:80/"
languageCode = 'en-us'
title = 'Max Wolffe'
[module]
[[module.imports]]
    path = 'github.com/theNewDynamic/gohugo-theme-ananke'
resourceDir = "../resources"

SectionPagesMenu = "main"
DefaultContentLanguage = "en"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "A man a plan a canal, Panama"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3